- name: declaring variable at play level
  hosts: all
  connection: local
  vars:
    URL: play.example.com
  tasks:
    - name: access variable at play level
      ansible.builtin.debug:
        msg: URL == {{URL}}

- name: declaring variable at file level
  hosts: all
  connection: local
  vars_files:
    - var.yml
  tasks:
    - name: access variable at file level
      ansible.builtin.debug:
        msg: URL == {{URL}}


- name: declaring variable at task level
  hosts: all
  connection: local
  tasks:
    - name: access variable at task level
      ansible.builtin.debug:
        msg: URL == {{URL}}
      vars:
          URL: task.example.com
